OpenGMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic

from core import views as core_views
from authentication import views as client_auth_views
from client import views as client_views
import notifications.urls
from autocompleteAPI import views as autocomplete_views
from elastic_search import views as seach_views
from user_group import check_group

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'^login', core_views.login_view, name='login'),

    url(r'^signup/$', client_auth_views.signup, name='signup'),
    url(r'^account_activation_sent/$', client_auth_views.account_activation_sent,
        name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        client_auth_views.activate, name='activate'),
    url(r'^/pass?=success/', client_auth_views.regSuccess, name='/pass?=success/'),

    # url(r'^all_products/$', core_views.allproducts, name='all_products'),

    url(r'^auth/', include('authentication.urls')),
    url(r'^officer/', include('officer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^service/', include('service.urls')),

    # products url
    url(r'^products', client_views.products, name='products'),
    url(r'^(?P<slug>[\w-]+)/detail/', client_views.product_details, name='detail'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^(?P<pk>[0-9]+)/review', client_views.review, name='review'),

    # cart url
    url(r'^cart/', include('cart.urls', namespace='cart')),

    # order url
    url(r'^order/', include('order.urls', namespace='order')),

    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

    # notification
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # search
    url('^search', seach_views.search, name='search'),

    # rest API for autocomplete
    url('^api.alif-marine.com/search/products/', autocomplete_views.list, name='productsAPI'),
]

handler404 = 'user_group.check_group.handler404'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

client/urls.py
from django.conf.urls import url
from django.views import generic
import client.views as client_views

app_name = 'client'

urlpatterns = [
    # url(r'^dash/$', generic.FormView.as_view(
    #     form_class=form.RegistrationForm, template_name="dashboard/create_account.html")),

    url(r'^profile', client_views.profile, name='profile'),
    url(r'^contact', client_views.contact, name='contact'),
    url(r'^picture', client_views.picture, name='picture'),
    url(r'^password', client_views.password, name='password'),

    # url(r'^create_account', client_views.create_account, name='create_account'),
    # url(r'^delete_account', client_views.delete_account, name='delete_account'),
    # url(r'^reset_account_pass', client_views.reset_account_pass, name='reset_account_pass'),

    url(r'^new_order', client_views.new_order, name='new_order'),
    url(r'^order_list', client_views.order_list, name='order_list'),
    url(r'^(?P<pk>[0-9]+)/order_view', client_views.order_view, name='order_view'),
    url(r'^order_edit', client_views.order_edit, name='order_edit'),

    url(r'^notification', client_views.notification, name='notification'),

    url(r'^logout', client_views.logout_view, name='logout'),
]

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^status?=success/$', views.success, name='success'),
    # url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    # url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='admin_order_pdf'),
]

Notifications/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from order.models import Order

# Create your models here.


class Notifications(models.Model):
    from_user = models.ForeignKey(User, related_name='+')
    to_user = models.ForeignKey(User, related_name='+')
    order = models.ForeignKey(Order, related_name='+', blank=True, default=1)
    notification_message = models.TextField(max_length=250, null=True)
    notification_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Notifications'

client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from notifications.signals import notify
from authentication.models import Employee

# Create your models here.


def my_handler(sender, instance, created, **kwargs):
    notify.send(instance, verb='was saved')


post_save.connect(my_handler, sender=Employee.user)


class Order_List(models.Model):
    order_id = models.IntegerField()
    username = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    order_date = models.DateField()
    delivery_date = models.DateField()
    action = models.CharField(max_length=100)

order/forms.py
from django import forms
from .models import Order
from phonenumber_field.formfields import PhoneNumberField


class OrderCreateForm(forms.ModelForm):
    phone = PhoneNumberField(widget=forms.TextInput(attrs={'placeholder': '+8801XXXXXXXXX'}), label="Phone number",
                             required=False)

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'zip', 'city']

Notifications/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

client/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
import os
from PIL import Image
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect, render
from client.form import ProfileForm, ChangePasswordForm, ContactForm, NewOrderForm
from officer.models import ProductList, ProductReview
from star_ratings.models import Rating
from cart.forms import CartAddProductForm
from django.shortcuts import render
from django_tables2 import RequestConfig
from order.models import Order, OrderItem
from user_group.check_group import group_required
from django.contrib.auth import logout
from Notifications.models import Notifications
# from .tables import OrderTable

__FILE_TYPES = ['zip']


@login_required(login_url='/login/')
@group_required('client_group')
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            # user.birth_date = form.cleaned_data.get('birth_date')
            # user.profile.job_title = form.cleaned_data.get('job_title')  # profile is for user profile
            user.profile.sex = form.cleaned_data.get('sex')
            user.email = form.cleaned_data.get('email')
            # user.profile.url = form.cleaned_data.get('url')
            # user.profile.location = form.cleaned_data.get('location')
            user.profile.about = form.cleaned_data.get('about')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')

    else:
        # form = ProfileForm(instance=user, initial={
        #     'job_title': user.profile.job_title,
        #     'url': user.profile.url,
        #     'location': user.profile.location
        #     })
        form = ProfileForm(instance=user, initial={
            'sex': user.profile.sex,
            'about': user.profile.about,
        })
    return render(request, 'client/client_profile.html', {'form': form})


@login_required(login_url='/login/')
@group_required('client_group')
def contact(request):
    user = request.user
    if request.method == 'POST':
        # form = ContactForm()
        form = ContactForm(request.POST)
        if form.is_valid():
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.state = form.cleaned_data.get('state')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.phone = form.cleaned_data.get('phone')
            user.profile.zip = form.cleaned_data.get('zip')

            # user.birth_date = form.cleaned_data.get('birth_date')
            # user.profile.job_title = form.cleaned_data.get('job_title')  # profile is for user profile
            # user.sex = form.cleaned_data.get('sex')
            # user.email = form.cleaned_data.get('email')
            # user.profile.url = form.cleaned_data.get('url')
            # user.profile.location = form.cleaned_data.get('location')
            # user.profile.about = form.cleaned_data.get('about')

            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your contact was successfully edited.')

    else:
        # form = ProfileForm(instance=user, initial={
        #     'job_title': user.profile.job_title,
        #     'url': user.profile.url,
        #     'location': user.profile.location
        #     })
        form = ContactForm(instance=user, initial={
            'address': user.profile.address,
            'city': user.profile.city,
            'state': user.profile.state,
            'country': user.profile.country,
            'phone': user.profile.phone,
            'zip': user.profile.zip,
        })
    return render(request, 'client/client_contact.html', {'form': form})


@login_required(login_url='/login/')
@group_required('client_group')
def picture(request):
    user = request.user
    profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
    if not os.path.exists(profile_pictures):
        os.makedirs(profile_pictures)
    if request.method == 'POST':
        _picture = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_' + str(request.user.id) + '.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in _picture.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 400:
            new_width = 400
            new_height = 300       # (height * 400) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        user.profile.profile_picture = filename
        user.save()
        return render(request, 'client/client_picture.html')
    return render(request, 'client/client_picture.html')


@login_required(login_url='/login/')
@group_required('client_group')
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password/')

    else:
        form = ChangePasswordForm(instance=user)
    # form = ChangePasswordForm()
    return render(request, 'client/client_password.html', {'form': form})


# def create_account(request):
#     return render(request, 'dashboard/create_account.html')
#
#
# def delete_account(request):
#     return render(request, 'dashboard/delete_account.html')
#
#
# def reset_account_pass(request):
#     return render(request, 'dashboard/reset_account_pass.html')

@login_required(login_url='/login/')
@group_required('client_group')
def new_order(request):
    form = NewOrderForm()
    return render(request, 'client/client_new_order.html', {'form': form})


@login_required(login_url='/login/')
def order_list(request):
    user = request.user
    orders = Order.objects.filter(email=user.email)
    print (orders)
    return render(request, 'client/order_list.html', {'orders': orders})


@login_required(login_url='/login/')
@group_required('client_group')
def order_view(request, pk):
    user = request.user
    order = Order.objects.get(id=pk)
    order_item = OrderItem.objects.filter(order_id=pk)
    return render(request, 'client/order_view.html', {'order_item': order_item,
                                                      'order': order})


@login_required(login_url='/login/')
@group_required('client_group')
def order_edit(request):
    form = NewOrderForm()
    return render(request, 'client/order_edit.html', {'form': form})


# view for all products. Even if a user is not authenticated, can view this page. Can view details of the
# product. But cannot use 'add to cart' privilege!!!


def products(request):
    _products = ProductList.objects.all()
    paginator = Paginator(_products, 9)
    page = request.GET.get('page', 1)  # returns the 1st page
    try:
        product_list = paginator.page(page)
    except PageNotAnInteger:
        product_list = paginator.page(1)
    except EmptyPage:
        product_list = paginator.page(paginator.num_pages)

    return render(request, 'client/all_products.html', {'product_list': product_list})


def product_details(request, slug):
    product = get_object_or_404(ProductList, slug=slug)
    product_review = ProductReview.objects.filter(product_id=product.product_id)
    rating_count = Rating.objects.filter(object_id=product.id)
    # print (product_review.values(review))
    cart_product_form = CartAddProductForm()
    return render(request, 'client/products_detail.html', {
        'product': product,
        'product_review': product_review,
        'rating_count': rating_count,
        'cart_product_form': cart_product_form,
    })


@group_required('client_group')
def review(request, pk):
    user = request.user
    product = get_object_or_404(ProductList, id=pk)
    # print (product)
    rating = Rating.objects.get(object_id=pk)
    # print ('rating is {}'.format(rating))
    product_review = ProductReview()
    product_review.product_id = product.product_id
    product_review.product_name = product.product_name
    # print('rating {}'.format(rating.object_id))
    product_review.rank = rating.total
    product_review.reviewed_by = user
    product_review.review = request.POST.get('comment')
    product_review.save()
    return redirect('detail', slug=product.slug)


@login_required
@group_required('client_group')
def notification(request):
    user = request.user
    unread = user.notifications.unread()
    __notification = Notifications()
    for msg in unread:
        __notification.from_user = msg.actor
        __notification.to_user = user
        __notification.order = msg.action_object
        __notification.notification_message = msg.verb
        __notification.notification_time = msg.timestamp
        print(msg.timestamp)
        __notification.save()
    all_notifications = Notifications.objects.filter(to_user=user)

client/templates/client/client_contact.html
{% extends 'client/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Edit Profile' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'client:contact' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

client/templates/client/client_new_order.html
{% extends 'client/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'New Order' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'New Order' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'client:new_order' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

client/templates/client/client_password.html
{% extends 'client/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Password' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'client:password' %}">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

client/templates/client/dash.html
{% load staticfiles %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dashboard</title>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <!-- Bootstrap -->
   <link href="{% static 'extra/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
     <link href="{% static 'extra/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
      <!-- NProgress -->
   <link href="{% static 'extra/nprogress.css' %}" rel="stylesheet">
   {% block head %}
   {% endblock %}
    <!-- jQuery custom content scroller -->
   <link href="{% static 'extra/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
   <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">




  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'home' %}" class="site_title">
                  <i class="fa fa-paw"></i>
                  <span>Alif-Marine-Engineers Ltd.</span>
              </a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{ user.profile.get_picture }}" alt="..."  class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ user.profile.get_screen_name }}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h2>Client Module</h2>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-edit"></i> Update Info <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'client:profile'%}"> Profile </a></li>
                        <li><a href="{% url 'client:contact'%}"> Contact Info </a></li>
                        <li><a href="{% url 'client:picture' %}"> Picture </a></li>
                        <li><a href="{% url 'client:password' %}"> Password </a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-plus"></i> Submit New Order
                    <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'client:new_order' %}"> New Order </a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-info"></i> Order History
                    <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'client:order_list' %}"> Order List </a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-bar-chart-o"></i> Data Status <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#"> Status </a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle"
                     data-toggle="dropdown" aria-expanded="false">
                    <img src="{{ user.profile.get_picture }}" alt="">
                    {{ user.profile.get_screen_name }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="{% url 'client:logout' %}"><i class="fa fa-sign-out pull-right"></i>
                        Log Out</a>
                    </li>
                  </ul>
                </li>
                <li role="presentation" class="dropdown">
                  <a href="{% url 'client:notification' %}" id="notifications" title="Notification">
                    <i class="fa fa-bell-o"></i>
                    {% live_notify_badge classes="badge" %}
                    {% register_notify_callbacks  callbacks='fill_notification_list,fill_notification_badge'%}
                    {% live_notify_list classes="dropdown-menu" %}
                  </a>
                </li>

              </ul>

            </nav>
          </div>
        </div>
        <!-- /top navigation -->


        <!-- page content -->
        <div class="right_col" role="main">
              <div class="container expand-on-small-only">
                {% block content %}{% endblock %}
              </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

{#    <!-- jQuery -->#}
{#    {% include 'dashboard/extra/jquery/dist/jquery.min.js' %}#}
{#    <script src="extra/jquery/dist/jquery.min.js"></script>#}
{#    <!-- Bootstrap -->#}
{#    {% include 'dashboard/extra/bootstrap/dist/js/bootstrap.min.js' %}#}
{#    <script src="extra/bootstrap/dist/js/bootstrap.min.js"></script>#}
{#    <!-- FastClick -->#}
{#    {% include 'dashboard/extra/fastclick/lib/fastclick.js' %}#}
{#    <script src="extra/fastclick/lib/fastclick.js"></script>#}
{#    <!-- NProgress -->#}
{#    {% include 'dashboard/extra/nprogress/nprogress.js' %}#}
{#    <script src="extra/nprogress/nprogress.js"></script>#}
{#    <!-- jQuery custom content scroller -->#}
{#    {% include 'dashboard/extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}#}
{#    <script src="extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>#}
{##}
{#    <!-- Custom Theme Scripts -->#}
{#    {% include 'dashboard/build/js/custom.min.js' %}#}
{#    <script src="build/js/custom.min.js"></script>#}

  <script src="{% static 'extra/jquery/dist/jquery.min.js' %}"></script>
{#    <link href="extra/bootstrap.min.css" rel="stylesheet">#}
    <!-- Font Awesome -->
    <script src="{% static 'extra/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#    <link href="extra/font-awesome/css/font-awesome.min.css" rel="stylesheet">#}
    <!-- NProgress -->
    <script src="{% static 'extra/fastclick/lib/fastclick.js' %}"></script>

{#    <link href="extra/nprogress.css" rel="stylesheet">#}
    <!-- jQuery custom content scroller -->
  <script src="{% static 'extra/nprogress/nprogress.js' %}"></script>
  <script src="{% static 'extra/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>


{#  {% include 'dashboard/extra/jquery.mCustomScrollbar.min.css' %}#}
{#    <link href="extra/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>#}

    <!-- Custom Theme Style -->
  <script src="{% static 'extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>

{#  {% include 'dashboard/build/css/custom.min.css' %}#}
    <script src="{% static 'build/js/custom.min.js' %}"></script>
      {% block js %}
    {% endblock %}
  </body>
</html>