OpenGMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic

from core import views as core_views
from authentication import views as client_auth_views
from client import views as client_views
import notifications.urls
from autocompleteAPI import views as autocomplete_views
from elastic_search import views as seach_views
from user_group import check_group

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'^login', core_views.login_view, name='login'),

    url(r'^signup/$', client_auth_views.signup, name='signup'),
    url(r'^account_activation_sent/$', client_auth_views.account_activation_sent,
        name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        client_auth_views.activate, name='activate'),
    url(r'^/pass?=success/', client_auth_views.regSuccess, name='/pass?=success/'),

    # url(r'^all_products/$', core_views.allproducts, name='all_products'),

    url(r'^auth/', include('authentication.urls')),
    url(r'^officer/', include('officer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^service/', include('service.urls')),

    # products url
    url(r'^products', client_views.products, name='products'),
    url(r'^(?P<slug>[\w-]+)/detail/', client_views.product_details, name='detail'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^(?P<pk>[0-9]+)/review', client_views.review, name='review'),

    # cart url
    url(r'^cart/', include('cart.urls', namespace='cart')),

    # order url
    url(r'^order/', include('order.urls', namespace='order')),

    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

    # notification
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # search
    url('^search', seach_views.search, name='search'),

    # rest API for autocomplete
    url('^api.alif-marine.com/search/products/', autocomplete_views.list, name='productsAPI'),
]

handler404 = 'user_group.check_group.handler404'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

officer/urls.py

from django.conf.urls import url
from django.views import generic
import officer.views as officer_views

app_name = 'officer'

urlpatterns = [
    # url(r'^dash/$', generic.FormView.as_view(
    #     form_class=form.RegistrationForm, template_name="dashboard/create_account.html")),

    url(r'^profile', officer_views.profile, name='profile'),
    url(r'^contact', officer_views.contact, name='contact'),
    url(r'^picture', officer_views.picture, name='picture'),
    url(r'^password', officer_views.password, name='password'),

    url(r'^create_account', officer_views.create_account, name='create_account'),
    url(r'^delete_account', officer_views.delete_account, name='delete_account'),
    url(r'^reset_account_pass', officer_views.reset_account_pass, name='reset_account_pass'),

    url(r'^new_order', officer_views.new_order, name='new_order'),
    url(r'^order_list', officer_views.order_list, name='order_list'),

    url(r'^add_product', officer_views.add_product, name='add_product'),
    url(r'^all_products', officer_views.all_products, name='all_products'),
    url(r'^(?P<slug>[\w-]+)/detail/', officer_views.product_details, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/', officer_views.product_edit, name='edit'),

    url(r'^logout', officer_views.logout_view, name='logout'),
]

officer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
# from .search import ProductIndex
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
import hashlib
import os.path
import urllib
from django.conf import settings
# Create your models here.


class Order_List(models.Model):
    order_id = models.IntegerField()
    username = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    order_date = models.DateField()
    delivery_date = models.DateField()
    action = models.CharField(max_length=100)


class ProductList(models.Model):
    product_id = models.IntegerField()
    product_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=40)
    uploaded_by = models.ForeignKey(User, related_name='+')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    product_image = models.FileField(upload_to='media/')
    choice = (('available', 'available'), ('unavailable', 'unavailable'))
    product_available = models.CharField(max_length=15, choices=choice)
    product_porichiti = models.CharField(max_length=100, null=True, blank=True) # I am really out of variable names
    product_description = models.CharField(max_length=300, null=True, blank=True)
    product_notes = models.CharField(max_length=300, null=True, blank=True)
    product_features = models.CharField(max_length=300, null=True, blank=True)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'product_list'
        ordering = "-uploaded_at",

    def __str__(self):
        return self.product_name

    # Method for indexing the model
    def indexing(self):
        from .search import ProductIndex
        obj = ProductIndex(
            meta={'id': self.id},
            product_id=self.product_id,
            product_name=self.product_name,
            slug=self.slug,
            # uploaded_by=self.uploaded_by,
            # uploaded_at=self.uploaded_at,
            product_available=self.product_available,
            product_porichiti=self.product_porichiti,
            product_description=self.product_description,
            product_notes=self.product_notes,
            product_features=self.product_features,
            quantity=self.quantity,
            price=self.price
        )
        obj.save(index='product-index')
        return obj.to_dict(include_meta=True)


@receiver(post_save, sender=ProductList)
def index_post(sender, instance, **kwargs):
    instance.indexing()


class ProductReview(models.Model):
    product_id = models.IntegerField()
    product_name = models.CharField(max_length=100)
    rank = models.IntegerField(default=0)
    review = models.CharField(max_length=250, null=True)
    reviewed_by = models.CharField(max_length=100)
    reviewed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'product_review'

officer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
import os
from PIL import Image
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect, render
from user_group.check_group import group_required
from officer.form import ProfileForm, ChangePasswordForm, ContactForm, NewOrderForm, ProductForm
from django.shortcuts import render
from django_tables2 import RequestConfig
from .models import ProductList
from .tables import OrderTable
from django.contrib.auth import logout

# Create your views here.


__FILE_TYPES = ['zip']


@login_required
@group_required('officer_group')
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            # user.birth_date = form.cleaned_data.get('birth_date')
            # user.profile.job_title = form.cleaned_data.get('job_title')  # profile is for user profile
            user.profile.sex = form.cleaned_data.get('sex')
            user.email = form.cleaned_data.get('email')
            # user.profile.url = form.cleaned_data.get('url')
            # user.profile.location = form.cleaned_data.get('location')
            user.profile.about = form.cleaned_data.get('about')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')

    else:
        # form = ProfileForm(instance=user, initial={
        #     'job_title': user.profile.job_title,
        #     'url': user.profile.url,
        #     'location': user.profile.location
        #     })
        form = ProfileForm(instance=user, initial={
            'sex': user.profile.sex,
            'about': user.profile.about,
        })
    return render(request, 'dashboard/profile.html', {'form': form})


@login_required
@group_required('officer_group')
def contact(request):
    user = request.user
    if request.method == 'POST':
        # form = ContactForm()
        form = ContactForm(request.POST)
        if form.is_valid():
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.state = form.cleaned_data.get('state')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.phone = form.cleaned_data.get('phone')
            user.profile.zip = form.cleaned_data.get('zip')

            # user.birth_date = form.cleaned_data.get('birth_date')
            # user.profile.job_title = form.cleaned_data.get('job_title')  # profile is for user profile
            # user.sex = form.cleaned_data.get('sex')
            # user.email = form.cleaned_data.get('email')
            # user.profile.url = form.cleaned_data.get('url')
            # user.profile.location = form.cleaned_data.get('location')
            # user.profile.about = form.cleaned_data.get('about')

            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your contact was successfully edited.')

    else:
        # form = ProfileForm(instance=user, initial={
        #     'job_title': user.profile.job_title,
        #     'url': user.profile.url,
        #     'location': user.profile.location
        #     })
        form = ContactForm(instance=user, initial={
            'address': user.profile.address,
            'city': user.profile.city,
            'state': user.profile.state,
            'country': user.profile.country,
            'phone': user.profile.phone,
            'zip': user.profile.zip,
        })
    return render(request, 'dashboard/contact.html', {'form': form})


@login_required
@group_required('officer_group')
def picture(request):
    user = request.user
    profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
    if not os.path.exists(profile_pictures):
        os.makedirs(profile_pictures)
    if request.method == 'POST':
        _picture = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_' + str(request.user.id) + '.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in _picture.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 400:
            new_width = 400
            new_height = 300  # (height * 400) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        user.profile.profile_picture = filename
        user.save()
        return render(request, 'dashboard/picture.html')
    return render(request, 'dashboard/picture.html')


@login_required
@group_required('officer_group')
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password/')

    else:
        form = ChangePasswordForm(instance=user)
    return render(request, 'dashboard/password.html', {'form': form})


@login_required
@group_required('officer_group')
def create_account(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        # email = request.POST.get('email', False)
        account_type = request.POST.get('account_type')
        print (username)
        # print (email)
        print (account_type)

        account_types = {'Technical Officer': 1, 'Service Manager': 2, 'Production Manager': 3}
        if username and account_type != 'Account Type':
            if not User.objects.filter(username=username).exists():
                rand_password = User.objects.make_random_password(length=10, allowed_chars='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789')
                print("Generated Password " + rand_password)
                user = User.objects.create_user(username=username, password=rand_password)
                user.profile.account_type = account_types[account_type]
                user.save()
                print('user is saved')
                # NewUser(user=user, password=password).save()
                # messages.success(request, 'Created account successfully.')
                messages.add_message(request,
                                     messages.SUCCESS,
                                     "Account is created successfully!")
                return redirect('/officer/create_account')
            else:
                # messages.error(request, 'Submitted form is not valid. User already exist.')
                messages.add_message(request,
                                     messages.ERROR,
                                     "Submitted form is not valid. User already exist!")
                return redirect('/officer/create_account')

        else:
            # messages.error(request, 'Submitted form is not valid. Try again.')
            messages.add_message(request,
                                 messages.ERROR,
                                 "Submitted form is not valid! Try again.")
            return render(request, 'dashboard/create_account.html')
    else:
        return render(request, 'dashboard/create_account.html')


@group_required('officer_group')
def delete_account(request):
    return render(request, 'dashboard/delete_account.html')


@group_required('officer_group')
def reset_account_pass(request):
    return render(request, 'dashboard/reset_account_pass.html')


@group_required('officer_group')
def new_order(request):
    form = NewOrderForm()
    return render(request, 'dashboard/new_order.html', {'form': form})


@group_required('officer_group')
def order_list(request):
    # table = OrderTable(Order_List.objects.all())
    # RequestConfig(request).configure(table)
    return render(request, 'dashboard/order_list.html')


@login_required
@group_required('officer_group')
def add_product(request):
    user = request.user
    product_list = ProductList()
    if request.method == 'POST':
        print ('yoo')
        form = ProductForm(request.POST, request.FILES)
        print ('yoo')
        print (form)
        if form.is_valid():
            print ('yoo')
            product_list.product_id = form.cleaned_data.get('product_id')
            print (product_list.product_id)
            product_list.product_name = form.cleaned_data.get('product_name')
            product_list.uploaded_by = user
            product_list.quantity = form.cleaned_data.get('quantity')
            product_list.price = form.cleaned_data.get('price')
            product_list.product_available = form.cleaned_data.get('product_available')
            product_list.product_description = form.cleaned_data.get('product_description')
            product_list.product_porichiti = form.cleaned_data.get('product_porichiti')

officer/templates/dashboard/add_products.html
{% extends 'dashboard/test.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
    <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Product Module</h3>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Add an Item</h2>

                    <div class="clearfix"></div>

                  </div>
                  <div class="x_content">
                    <div class="col-md-9 col-sm-9 col-xs-12">

                      <div class="profile_title">
                        <div class="col-md-6">
                          <h2>Product Description</h2>
                        </div>
                      </div>
                          <form role="form" class="form-horizontal" method="post" action="{% url 'officer:add_product' %}"
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form.visible_fields %}
                                <div class="form-group{% if field.errors %} has-error{% endif %}">
                                    <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                                    <div class="col-sm-10">
                                        {{ field }}
                                        {% if field.help_text %}
                                            <span class="help-block">{{ field.help_text }}</span>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <label class="control-label">{{ error }}</label>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                  </div>
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}

{% block js %}
{% endblock %}

officer/templates/dashboard/all_products.html
{% extends 'dashboard/test.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
    <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3> All Products </h3>
                </div>
                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-16">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>List of All Products</h2>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                    <div class="row">

{#                    edit from here  #}
                      {% if product_list %}
                          {% for product in product_list %}
                            <div class="col-md-55">
                                <div class="thumbnail">
                                    <div class="image view view-first">
                                        <img style="width: 100%; display: block;" src="{{ product.product_image.url }}" alt="image" />
                                        <div class="mask">
                                            <p>{{ product.product_name }}</p>
                                            <div class="tools tools-bottom">
                                                <a href="{% url 'officer:detail' product.slug%}"><i class="fa fa-link" title="Details"></i></a>
                                                {% if user %}
                                                    <a href="{% url 'officer:edit' product.slug%}"><i class="fa fa-pencil" title="Edit"></i></a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="caption">
                                        <p>{{ product.product_name }}</p>
                                    </div>
                                </div>
                            </div>
                          {% endfor %}
{#                    upto here#}
                      {% endif %}

                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}

{% block js %}
{% endblock %}

officer/templates/dashboard/contact.html
{% extends 'dashboard/test.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Edit Profile' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'officer:contact' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

officer/templates/dashboard/create_account.html
{% extends 'dashboard/test.html' %}
{% load staticfiles %}
{#{% load material_form %}#}

{% block head %}

    <!-- Animate.css -->
    <link href="{% static 'extra/animate.css/animate.min.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form action="{% url "officer:create_account" %}" method="post">
              {% csrf_token %}
              <h1>Create Account</h1>
              <div>
                <input type="text" class="form-control" name="username" placeholder="Username" required="" />
              </div>
{#              <div>#}
{#                <input type="email" class="form-control" name="email" placeholder="Email" required="" />#}
{#              </div>#}
              <div class="form-group">

                        <div >
                          <select class="form-control" name="account_type">
                            <option>Account Type</option>
{#                            <option>Client</option>#}
                            <option>Service Manager</option>
                            <option>Production Manager</option>
                            <option>Technical Officer</option>
                          </select>
                        </div>
              </div>
              <div>
                <button class="btn btn-dark">Create Account</button>
              </div>

              <div class="separator">
              </div>
            </form>
          </section>
        </div>

      </div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}

officer/templates/dashboard/edit_product.html
{% extends 'dashboard/test.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
    <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Product Module</h3>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Edit {{ product.product_name }}</h2>

                    <div class="clearfix"></div>

                  </div>
                  <div class="x_content">
                    <div class="col-md-9 col-sm-9 col-xs-12">

                      <div class="profile_title">
                        <div class="col-md-6">
                          <h2>Product Description</h2>
                        </div>
                      </div>
                          <form role="form" class="form-horizontal" method="post" action="{% url 'officer:edit' product.slug%}"
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form.visible_fields %}
                                <div class="form-group{% if field.errors %} has-error{% endif %}">
                                    <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                                    <div class="col-sm-10">
                                        {{ field }}
                                        {% if field.help_text %}
                                            <span class="help-block">{{ field.help_text }}</span>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <label class="control-label">{{ error }}</label>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                  </div>
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
          </div>
        </div>
        <!-- /page content -->
{% endblock %}

{% block js %}
{% endblock %}