OpenGMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic

from core import views as core_views
from authentication import views as client_auth_views
from client import views as client_views
import notifications.urls
from autocompleteAPI import views as autocomplete_views
from elastic_search import views as seach_views
from user_group import check_group

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'^login', core_views.login_view, name='login'),

    url(r'^signup/$', client_auth_views.signup, name='signup'),
    url(r'^account_activation_sent/$', client_auth_views.account_activation_sent,
        name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        client_auth_views.activate, name='activate'),
    url(r'^/pass?=success/', client_auth_views.regSuccess, name='/pass?=success/'),

    # url(r'^all_products/$', core_views.allproducts, name='all_products'),

    url(r'^auth/', include('authentication.urls')),
    url(r'^officer/', include('officer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^service/', include('service.urls')),

    # products url
    url(r'^products', client_views.products, name='products'),
    url(r'^(?P<slug>[\w-]+)/detail/', client_views.product_details, name='detail'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^(?P<pk>[0-9]+)/review', client_views.review, name='review'),

    # cart url
    url(r'^cart/', include('cart.urls', namespace='cart')),

    # order url
    url(r'^order/', include('order.urls', namespace='order')),

    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

    # notification
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # search
    url('^search', seach_views.search, name='search'),

    # rest API for autocomplete
    url('^api.alif-marine.com/search/products/', autocomplete_views.list, name='productsAPI'),
]

handler404 = 'user_group.check_group.handler404'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^status?=success/$', views.success, name='success'),
    # url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    # url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='admin_order_pdf'),
]

production/urls.py
from django.conf.urls import url
from django.views import generic
import production.views as production_views

app_name = 'production'

urlpatterns = [
    # url(r'^dash/$', generic.FormView.as_view(
    #     form_class=form.RegistrationForm, template_name="dashboard/create_account.html")),

    url(r'^profile', production_views.profile, name='profile'),
    url(r'^contact', production_views.contact, name='contact'),
    url(r'^picture', production_views.picture, name='picture'),
    url(r'^password', production_views.password, name='password'),

    url(r'^new_order', production_views.new_order, name='new_order'),
    url(r'^order_list', production_views.order_list, name='order_list'),

    url(r'^(?P<pk>[0-9]+)/order_view', production_views.order_view, name='order_view'),
    url(r'^(?P<pk>[0-9]+)/order_edit', production_views.order_edit, name='order_edit'),

    url(r'^notification', production_views.notification, name='notification'),

    url(r'^logout', production_views.logout_view, name='logout'),
]

Notifications/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.contrib import messages
# import weasyprint
from .models import Order, OrderItem
from .forms import OrderCreateForm
# from .tasks import order_created
from cart.cart import Cart
from notifications.signals import notify
from authentication.models import Employee, User, Profile, Client


def order_create(request):
    user = request.user
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            _email = form.cleaned_data['email']
            print (_email)
            print (user.email)
            if _email != user.email:
                print ("error")
                messages.add_message(request, messages.ERROR,
                                     "Your email doesn't match. Please provide the email you used"
                                     "to open this account")
                return render(request, 'order/create.html', {'form': form})
            else:
                order = form.save()
                for item in cart:
                    OrderItem.objects.create(order=order,
                                             product=item['product'],
                                             price=item['price'],
                                             quantity=item['quantity'])
            # clear the cart
                cart.clear()
            # launch asynchronous task
            # order_created.delay(order.id)
            # set the order in the session
                request.session['order_id'] = order.id
            # generate notification for production manager
                msg = "A new order has been added by user {0}".format(user.profile.get_screen_name())
                # profile = Employee.objects.filter(user=)
                # _recipient = Employee.objects.filter(user=User.objects.filter(profile__account_type=3))
                _recipient = User.objects.filter(profile__account_type=3)
                print ("notify to ")
                print(_recipient)
                notify.send(user, recipient=list(_recipient), verb=msg, action_object=order)
            # redirect to the payment
                return redirect('client:order_view', pk=order.id)  # change hobe(-->hoise)
        else:
            messages.add_message(request, messages.ERROR,
                                 'Submitted form contains invalid data!')
            return render(request, 'order/create.html', {'form': form})
    else:
        if cart:
            form = OrderCreateForm(instance=user, initial={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'email': user.email,
            })
            return render(request, 'order/create.html', {'cart': cart,
                                                         'form': form})
        else:
            messages.add_message(request, messages.ERROR,
                                 'Your Cart is Empty. Please Shop with us!')
            return render(request, 'cart/detail.html')


def success(request):
    return render(request, 'order/success.html')

production/views.py
# -*- coding: utf-8 -*-
from __future__ import print_function
from __future__ import unicode_literals
from django.shortcuts import render
import os
from PIL import Image
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect, render
from production.form import ProfileForm, ChangePasswordForm, ContactForm, NewOrderForm, StatusForm
from order.models import Order, OrderItem
from django.shortcuts import render
from user_group.check_group import group_required
from Notifications.models import Notifications
from notifications.signals import notify
import dateutil.parser
from django_tables2 import RequestConfig
from .models import Order_List


# Create your views here.


__FILE_TYPES = ['zip']


@login_required
@group_required('production_group')
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            # user.birth_date = form.cleaned_data.get('birth_date')
            # user.profile.job_title = form.cleaned_data.get('job_title')  # profile is for user profile
            user.profile.sex = form.cleaned_data.get('sex')
            user.email = form.cleaned_data.get('email')
            # user.profile.url = form.cleaned_data.get('url')
            # user.profile.location = form.cleaned_data.get('location')
            user.profile.about = form.cleaned_data.get('about')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')

    else:
        # form = ProfileForm(instance=user, initial={
        #     'job_title': user.profile.job_title,
        #     'url': user.profile.url,
        #     'location': user.profile.location
        #     })
        form = ProfileForm(instance=user, initial={
            'sex': user.profile.sex,
            'about': user.profile.about,
        })
    return render(request, 'production/profile.html', {'form': form})


@login_required
@group_required('production_group')
def contact(request):
    user = request.user
    if request.method == 'POST':
        # form = ContactForm()
        form = ContactForm(request.POST)
        if form.is_valid():
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.state = form.cleaned_data.get('state')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.phone = form.cleaned_data.get('phone')
            user.profile.zip = form.cleaned_data.get('zip')

            # user.birth_date = form.cleaned_data.get('birth_date')
            # user.profile.job_title = form.cleaned_data.get('job_title')  # profile is for user profile
            # user.sex = form.cleaned_data.get('sex')
            # user.email = form.cleaned_data.get('email')
            # user.profile.url = form.cleaned_data.get('url')
            # user.profile.location = form.cleaned_data.get('location')
            # user.profile.about = form.cleaned_data.get('about')

            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your contact was successfully edited.')

    else:
        # form = ProfileForm(instance=user, initial={
        #     'job_title': user.profile.job_title,
        #     'url': user.profile.url,
        #     'location': user.profile.location
        #     })
        form = ContactForm(instance=user, initial={
            'address': user.profile.address,
            'city': user.profile.city,
            'state': user.profile.state,
            'country': user.profile.country,
            'phone': user.profile.phone,
            'zip': user.profile.zip,
        })
    return render(request, 'production/contact.html', {'form': form})


@login_required
@group_required('production_group')
def picture(request):
    user = request.user
    profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
    if not os.path.exists(profile_pictures):
        os.makedirs(profile_pictures)
    if request.method == 'POST':
        _picture = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_' + str(request.user.id) + '.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in _picture.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 400:
            new_width = 400
            new_height = 300  # (height * 400) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        user.profile.profile_picture = filename
        user.save()
        return render(request, 'production/picture.html')
    return render(request, 'production/picture.html')


@login_required
@group_required('production_group')
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password/')

    else:
        form = ChangePasswordForm(instance=user)
    return render(request, 'production/password.html', {'form': form})


@group_required('production_group')
def new_order(request):
    form = NewOrderForm()
    return render(request, 'production/new_order.html', {'form': form})


@group_required('production_group')
def order_list(request):
    user = request.user
    orders = Order.objects.all()
    # print (orders)
    return render(request, 'production/order_list.html', {'orders': orders})


@login_required
@group_required('production_group')
def order_view(request, pk):
    user = request.user
    order = Order.objects.get(id=pk)
    order_item = OrderItem.objects.filter(order_id=pk)
    return render(request, 'production/order_view.html', {'order_item': order_item,
                                                          'order': order})


@login_required
@group_required('production_group')
def order_edit(request, pk):
    user = request.user
    order = Order.objects.get(id=pk)
    order_item = OrderItem.objects.filter(order_id=pk)
    if request.method == 'POST':
        print ('baal')
        form = StatusForm(request.POST)
        order.delivery = request.POST['date']
        print(order.delivery)
        if form.is_valid():
            order.status = form.cleaned_data.get('status')
            print(order.status)
            order.save()
            if order.delivery and order.status:
                msg = "Your order status has been updated and a delivery date has been set."
                _recipient = User.objects.filter(email=order.email)
                notify.send(user, recipient=_recipient, verb=msg, action_object=order)
            elif order.delivery and not order.status:
                msg = "A delivery date has been set for your order"
                _recipient = User.objects.filter(email=order.email)
                notify.send(user, recipient=_recipient, verb=msg)
            elif not order.delivery and order.status:
                msg = "Your order status has been updated."
                _recipient = User.objects.filter(email=order.email)
                notify.send(user, recipient=_recipient, verb=msg)
            return redirect('production:order_view', pk=pk)
    else:
        form = StatusForm()
        return render(request, 'production/order_edit.html', {'order_item': order_item,
                                                              'order': order, 'form': form})


@login_required
@group_required('production_group')
def notification(request):
    user = request.user
    unread = user.notifications.unread()
    __notification = Notifications()
    for msg in unread:
        __notification.from_user = msg.actor
        __notification.to_user = user
        __notification.order = msg.action_object
        __notification.notification_message = msg.verb
        __notification.notification_time = msg.timestamp
        print(msg.timestamp)
        __notification.save()
    all_notifications = Notifications.objects.filter(to_user=user)
    paginator = Paginator(all_notifications, 10)
    page = request.GET.get('page', 1) # returns the 1st page
    try:
        notification_list = paginator.page(page)
    except PageNotAnInteger:
        notification_list = paginator.page(1)
    except EmptyPage:
        notification_list = paginator.page(paginator.num_pages)
    return render(request, 'production/notification.html', {
        'unread': unread,
        'notification_list': notification_list
    })


@login_required
@group_required('production_group')
def logout_view(request):
    logout(request)
    return render(request, 'core/login.html')

production/templates/production/contact.html
{% extends 'production/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Edit Profile' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'production:contact' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

production/templates/production/dash.html
{% load staticfiles %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dashboard</title>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <!-- Bootstrap -->
   <link href="{% static 'extra/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
     <link href="{% static 'extra/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
      <!-- NProgress -->
   <link href="{% static 'extra/nprogress.css' %}" rel="stylesheet">
   {% block head %}
   {% endblock %}
    <!-- jQuery custom content scroller -->
   <link href="{% static 'extra/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
   <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
   <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'home' %}" class="site_title"><i class="fa fa-paw"></i>
                  <span>Alif-Marine-Engineers Ltd.</span>
              </a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{ user.profile.get_picture }}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ user.profile.get_screen_name }}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h2>Production Manager Module</h2>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-edit"></i> Update Info
                      <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'production:profile'%}"> Profile </a></li>
                        <li><a href="{% url 'production:contact'%}"> Contact Info </a></li>
                        <li><a href="{% url 'production:picture' %}"> Picture </a></li>
                        <li><a href="{% url 'production:password' %}"> Password </a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-plus"></i> Submit New Order
                    <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'production:new_order' %}"> New Order </a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-info"></i> Order History
                    <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'production:order_list' %}"> Order List </a></li>
                    </ul>
                  </li>
                  <li>
                      <a>
                          <i class="fa fa-bar-chart-o"></i> Data Status
                          <span class="fa fa-chevron-down"></span>
                      </a>
                      <ul class="nav child_menu">
                          <li><a href="#"> Status </a></li>
                       </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle"
                     data-toggle="dropdown" aria-expanded="false">
                    <img src="{{ user.profile.get_picture }}" alt="">
                    {{ user.profile.get_screen_name }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="{% url 'production:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>
                <li role="presentation" class="dropdown">
                  <a href="{% url 'production:notification' %}" id="notifications" title="Notification">
                    <i class="fa fa-bell-o"></i>
                    {% live_notify_badge classes="badge" %}
                    {% register_notify_callbacks  callbacks='fill_notification_list,fill_notification_badge'%}
                    {% live_notify_list classes="dropdown-menu" %}
				{#	{% live_notify_list list_class="dropdown-menu" %} #}
{#                    <span class="badge bg-green">6</span>#}
                  </a>
{#                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">#}
{#                    <li>#}
{#                      <div class="text-center">#}
{#                        <a>#}
{#                          <strong>See All Alerts</strong>#}
{#                          <i class="fa fa-angle-right"></i>#}
{#                        </a>#}
{#                      </div>#}
{#                    </li>#}
{#                  </ul>#}
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->


        <!-- page content -->
        <div class="right_col" role="main">
              <div class="container expand-on-small-only">
                {% block content %}{% endblock %}
              </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

{#    <!-- jQuery -->#}
{#    {% include 'dashboard/extra/jquery/dist/jquery.min.js' %}#}
{#    <script src="extra/jquery/dist/jquery.min.js"></script>#}
{#    <!-- Bootstrap -->#}
{#    {% include 'dashboard/extra/bootstrap/dist/js/bootstrap.min.js' %}#}
{#    <script src="extra/bootstrap/dist/js/bootstrap.min.js"></script>#}
{#    <!-- FastClick -->#}
{#    {% include 'dashboard/extra/fastclick/lib/fastclick.js' %}#}
{#    <script src="extra/fastclick/lib/fastclick.js"></script>#}
{#    <!-- NProgress -->#}
{#    {% include 'dashboard/extra/nprogress/nprogress.js' %}#}
{#    <script src="extra/nprogress/nprogress.js"></script>#}
{#    <!-- jQuery custom content scroller -->#}
{#    {% include 'dashboard/extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}#}
{#    <script src="extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>#}
{##}
{#    <!-- Custom Theme Scripts -->#}
{#    {% include 'dashboard/build/js/custom.min.js' %}#}
{#    <script src="build/js/custom.min.js"></script>#}

  <script src="{% static 'extra/jquery/dist/jquery.min.js' %}"></script>
{#    <link href="extra/bootstrap.min.css" rel="stylesheet">#}
    <!-- Font Awesome -->
    <script src="{% static 'extra/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#    <link href="extra/font-awesome/css/font-awesome.min.css" rel="stylesheet">#}
    <!-- NProgress -->
    <script src="{% static 'extra/fastclick/lib/fastclick.js' %}"></script>

{#    <link href="extra/nprogress.css" rel="stylesheet">#}
    <!-- jQuery custom content scroller -->
  <script src="{% static 'extra/nprogress/nprogress.js' %}"></script>
  <script src="{% static 'extra/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>

{#  {% include 'dashboard/extra/jquery.mCustomScrollbar.min.css' %}#}
{#    <link href="extra/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>#}

    <!-- Custom Theme Style -->
  <script src="{% static 'extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>

{#  {% include 'dashboard/build/css/custom.min.css' %}#}
  {% block js %}
  {% endblock %}
    <script src="{% static 'build/js/custom.min.js' %}"></script>
  </body>
</html>

production/templates/production/delete_account.html
{% extends 'production/dash.html' %}
{% load staticfiles %}
{#{% load material_form %}#}

{% block head %}

    <!-- Animate.css -->
    <link href="{% static 'extra/animate.css/animate.min.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}
<div>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form>
              <h1>Delete Account</h1>
              <div>
                <input type="text" class="form-control" placeholder="Username" required="" />
              </div>
              <div>
                <input type="password" class="form-control" placeholder="Your Password" required="" />
              </div>
              <div>
                <button class="btn btn-danger">Delete Account</button>
              </div>
              <div class="separator">
              </div>
            </form>
          </section>
        </div>

      </div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}

production/templates/production/new_order.html
{% extends 'production/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'New Order' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'New Order' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'production:new_order' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}